---
- name: List Docker Containers with command
  hosts: all
  gather_facts: no
  tasks:
    - name: Execute docker ps on specified Docker Host
      command: ps
      register: docker_ps_output

    - name: Print output of docker ps
      debug:
        msg: "{{ docker_ps_output.stdout_lines }}"
